# Generated by Django 2.0.7 on 2018-07-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_addphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='addaudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiosname', models.CharField(max_length=100)),
                ('audiosbrowse', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='addvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videosname', models.CharField(max_length=100)),
                ('videosbrowse', models.FileField(upload_to='')),
            ],
        ),
    ]
