# Generated by Django 2.0.7 on 2018-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_addaudios_addvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addaudios',
            new_name='addaudio',
        ),
        migrations.RenameModel(
            old_name='addvideos',
            new_name='addphoto',
        ),
        migrations.RenameModel(
            old_name='addphotos',
            new_name='addvideo',
        ),
        migrations.RenameField(
            model_name='addphoto',
            old_name='videosbrowse',
            new_name='photosbrowse',
        ),
        migrations.RenameField(
            model_name='addphoto',
            old_name='videosname',
            new_name='photosname',
        ),
        migrations.RenameField(
            model_name='addvideo',
            old_name='photosbrowse',
            new_name='videosbrowse',
        ),
        migrations.RenameField(
            model_name='addvideo',
            old_name='photosname',
            new_name='videosname',
        ),
    ]
